name: BikeShedLog
options:
  bundleIdPrefix: com.shimondeitel.bikeshedlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "2"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  BikeShedLog:
    type: application
    platform: iOS
    sources:
      - path: BikeShedLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bikeshedlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: BikeShedLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  BikeShedLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BikeShedLogTests
    dependencies:
      - target: BikeShedLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bikeshedlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  BikeShedLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BikeShedLogUITests
    dependencies:
      - target: BikeShedLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bikeshedlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  BikeShedLog:
    build:
      targets:
        BikeShedLog: all
        BikeShedLogTests: [test]
        BikeShedLogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: BikeShedLog.storekit
    test:
      config: Debug
      storeKitConfiguration: BikeShedLog.storekit
      targets:
        - BikeShedLogTests
        - BikeShedLogUITests
    archive:
      config: Release
